### ISSUE TITLE
Consultation about the use of daq

### ISSUE THREAD

**Issue by richars** [napatech/daq_dpdk_multiqueue#4]
some questions about the use of dpdk daq.

**Comment by mlilja01** [comment]
1) Once you start the DAQ you loose normal NIC behavior and cannot use the normal networking stack
2) You can't, all packets will be intercepted by the DAQ

**Comment by richars** [comment]
Hi. Thank you for your quick response.

**Comment by richars** [comment]
Hi. Tahnk you for your quick response.
 I had compiled the code, installed dpdk and bind the NIC to igb-uio. 
Original DPDK software runs correctly on my environment.
But when i execute the command:  snort --daq dpdk --daq-var dpdk_argc="-n4" -i "dpdk0",  I got an error message: Can't initialize DAQ dpdk (-3) - dpdk_daq_initialize: No Ethernet ports.
      Would you mind helping me to target the problem?
      Where and when can i find or name the interface  "dpdk0"?  Is the interface named when i bind the NIC to igb_uio ?
       Thank you very much.

**Comment by richars** [comment]
Hi. Tahnk you for your quick response.
 I had compiled the code, installed dpdk and bind the NIC to igb-uio. 
Original DPDK software runs correctly on my environment.
But when i execute the command:  snort --daq dpdk --daq-var dpdk_argc="-n4" -i "dpdk0",  I got an error message: Can't initialize DAQ dpdk (-3) - dpdk_daq_initialize: No Ethernet ports.
      Would you mind helping me to target the problem?
      Where and when can i find or name the interface  "dpdk0"?  Is the interface named when i bind the NIC to igb_uio ?
       Thank you very much.

**Comment by richars** [comment]
Hi. Tahnk you for your quick response.
 I had compiled the code, installed dpdk and bind the NIC to igb-uio. 
Original DPDK software runs correctly on my environment.
But when i execute the command:  snort --daq dpdk --daq-var dpdk_argc="-n4" -i "dpdk0",  I got an error message: Can't initialize DAQ dpdk (-3) - dpdk_daq_initialize: No Ethernet ports.
      Would you mind helping me to target the problem?
      Where and when can i find or name the interface  "dpdk0"?  Is the interface named when i bind the NIC to igb_uio ?
       Thank you very much.

**Comment by mlilja01** [comment]
As I remember it the 0 in dpdk0 refers to the first port that dpdk finds so it looks like no ports are found when dpdk initializes. What NIC are you using? Is the NIC supported by DPDK 16.07 which this daq was written for?

**Comment by richars** [comment]
the NIC in the host server is 82599ES 10-Gigabit SFI/SFP+ Network Connection 10fb.
the NIC in the vm is Ethernet controller: Red Hat, Inc Virtio network device.

**Comment by mlilja01** [comment]
Ok. They should work. Have you tried adding debug to the dpdk arguments "-n4 --log-level=eal,debug" or something like that?

**Comment by richars** [comment]
Original DPDK software runs correctly

**Comment by mlilja01** [comment]
Ok. Sorry I cannot help then

**Comment by richars** [comment]
thank you very much.
